name: Playwright Tests
on:
  push:
    branches: [main, master]
  pull_request:
    branches: [main, master]

jobs:
  test:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: pnpm/action-setup@v4
        with:
          version: 10
          run_install: false

      - uses: actions/setup-node@v4
        with:
          node-version: lts/*
          cache: 'pnpm'

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Cache Playwright Browsers
        uses: actions/cache@v4
        id: playwright-browsers-cache
        with:
          path: ~/.cache/ms-playwright
          key: playwright-browsers-${{ runner.os }}-${{ hashFiles('pnpm-lock.yaml') }}

      - name: Install Playwright Browsers
        if: steps.playwright-browsers-cache.outputs.cache-hit != 'true'
        run: pnpm exec playwright install --with-deps

      - name: Start server
        run: pnpm dev &

      - name: Wait for server
        run: pnpm dlx wait-on http://localhost:3000

      - name: Run Playwright tests
        run: NODE_ENV=development pnpm exec playwright test --workers=3

      - name: Kill Wait for server
        run: pkill -f wait-on

      - uses: actions/upload-artifact@v4
        if: ${{ !cancelled() }}
        with:
          name: playwright-report
          path: playwright-report/
          retention-days: 30
