name: Playwright Tests
on:
  push:
    branches: [main, master]
    paths-ignore:
      - '.github/workflows/playwright.yml'
      - '**.md'
  pull_request:
    branches: [main, master]
    paths-ignore:
      - '.github/workflows/playwright.yml'
      - '**.md'

env:
  NODE_ENV: development

jobs:
  E2E-Tests:
    if: |
      (github.event_name == 'push' && github.actor != 'dependabot[bot]') ||
      (github.event_name == 'pull_request' && 
      !contains(join(github.event.pull_request.labels.*.name), 'no-e2e') &&
      (github.actor != 'dependabot[bot]' || 
      contains(join(github.event.pull_request.labels.*.name), 'run-e2e')))
    timeout-minutes: 60
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: pnpm/action-setup@v4
        with:
          version: latest
          run_install: false

      - uses: actions/setup-node@v4
        with:
          node-version: lts/*
          cache: 'pnpm'

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Get Playwright version
        id: playwright-version
        run: echo "version=$(pnpm list @playwright/test --depth=0 | grep @playwright/test | cut -d@ -f3)" >> $GITHUB_OUTPUT

      - name: Cache Playwright browsers
        uses: actions/cache@v4
        id: playwright-cache
        with:
          path: ~/.cache/ms-playwright
          key: playwright-${{ runner.os }}-${{ steps.playwright-version.outputs.version }}
          restore-keys: |
            playwright-${{ runner.os }}-

      - name: Install Playwright Browsers (only if cache miss)
        if: steps.playwright-cache.outputs.cache-hit != 'true'
        run: pnpm exec playwright install --with-deps

      - name: Install Playwright system dependencies (if cache hit)
        if: steps.playwright-cache.outputs.cache-hit == 'true'
        run: pnpm exec playwright install-deps

      - name: Start server
        run: NODE_ENV=development pnpm dev &

      - name: Wait for server
        run: pnpm dlx wait-on http://localhost:3000 --timeout 60000

      - name: Run Playwright tests
        run: pnpm exec playwright test

      - uses: actions/upload-artifact@v4
        if: ${{ !cancelled() }}
        with:
          name: playwright-report
          path: playwright-report/
          retention-days: 30
