name: Playwright Tests
on:
  push:
    branches: [main, master]
    paths-ignore:
      - '.github/workflows/playwright.yml'
      - '**.md'
  pull_request:
    branches: [main, master]
    paths-ignore:
      - '.github/workflows/playwright.yml'
      - '**.md'

jobs:
  E2E-Tests:
    if: |
      (github.event_name == 'push' && github.actor != 'dependabot[bot]') ||
      (github.event_name == 'pull_request' && 
      !contains(join(github.event.pull_request.labels.*.name), 'no-e2e') &&
      (github.actor != 'dependabot[bot]' || 
      contains(join(github.event.pull_request.labels.*.name), 'run-e2e')))
    timeout-minutes: 60
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: pnpm/action-setup@v4
        with:
          version: latest
          run_install: false

      - uses: actions/setup-node@v4
        with:
          node-version: lts/*
          cache: 'pnpm'

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Install Playwright Browsers
        run: pnpm exec playwright install --with-deps

      - name: Start server
        run: pnpm dev &

      - name: Wait for server
        run: pnpm dlx wait-on http://localhost:3000

      - name: Run Playwright tests
        run: NODE_ENV=development pnpm exec playwright test

      - uses: actions/upload-artifact@v4
        if: ${{ !cancelled() }}
        with:
          name: playwright-report
          path: playwright-report/
          retention-days: 30
