name: Prevent Supabase Inactivity

on:
  schedule:
    - cron: '0 0 * * 0,3' # 일요일+수요일 자정 UTC
  workflow_dispatch:

jobs:
  ping:
    runs-on: ubuntu-latest
    env:
      SUPABASE_URL: ${{ secrets.NEXT_PUBLIC_SUPABASE_URL }}
      SUPABASE_KEY: ${{ secrets.NEXT_PUBLIC_SUPABASE_ANON_KEY }}
    steps:
      - run: |
          curl -X GET "${SUPABASE_URL}/rest/v1/questions?select=id&limit=1" \
            -H "apikey: ${SUPABASE_KEY}" \
            -H "Authorization: Bearer ${SUPABASE_KEY}"
