name: Prevent Supabase Inactivity

on:
  schedule:
    - cron: '0 0 * * 0,3' # 일요일+수요일 자정 UTC
  workflow_dispatch:

jobs:
  ping:
    runs-on: ubuntu-latest
    steps:
      - run: |
          curl -X GET "https://interview.kir93.co.kr/api/ping"
